# Generated by Django 2.2.16 on 2021-12-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
